# Generated by Django 3.2.6 on 2021-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nomecalendario', models.CharField(blank=True, db_column='NomeCalendario', max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, db_column='Municipio', max_length=150, null=True)),
                ('datacadastro', models.DateTimeField(db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(blank=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', null=True)),
            ],
            options={
                'db_table': 'Calendario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendarioferiado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, db_column='Ano', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='Mes', null=True)),
                ('dia', models.IntegerField(blank=True, db_column='Dia', null=True)),
                ('datacadastro', models.DateTimeField(db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(blank=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=150, null=True)),
            ],
            options={
                'db_table': 'CalendarioFeriado',
                'managed': False,
            },
        ),
    ]
