# Generated by Django 3.2.6 on 2021-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='calendarioferiado',
            options={},
        ),
    ]
