# Generated by Django 3.2.6 on 2021-08-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_calendarioferiado_calendarioid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='calendarioferiado',
            options={'managed': False},
        ),
    ]
