# Generated by Django 3.2.6 on 2021-08-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_auto_20210820_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendarioferiadoimport',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, db_column='Ano', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='Mes', null=True)),
                ('dia', models.IntegerField(blank=True, db_column='Dia', null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=150, null=True)),
            ],
            options={
                'db_table': 'CalendarioImport',
                'managed': True,
            },
        ),
    ]
