# Generated by Django 3.2.6 on 2021-08-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_calendarioferiadoimport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarioferiadoimport',
            options={},
        ),
        migrations.AlterModelTable(
            name='calendarioferiadoimport',
            table=None,
        ),
    ]
