# Generated by Django 3.2.6 on 2021-08-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisco', '0002_auto_20210820_1833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fisco',
            table='Fisco',
        ),
    ]
