# Generated by Django 3.2.6 on 2021-08-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisco', '0003_alter_fisco_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscofisco',
            fields=[
                ('id', models.CharField(db_column='id', max_length=32, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=50)),
                ('estado', models.CharField(db_column='estado', max_length=2)),
                ('municipio', models.CharField(db_column='municipio', max_length=150)),
                ('vencimento', models.DateTimeField(db_column='vencimento')),
                ('regratributo', models.IntegerField(db_column='regraTributo')),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='dataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='dataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='ativo', null=True)),
            ],
            options={
                'db_table': 'fisco_fisco',
                'managed': False,
            },
        ),
    ]
