# Generated by Django 3.2.6 on 2021-08-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisco', '0004_fiscofisco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisco',
            options={'managed': True},
        ),
    ]
