# Generated by Django 3.2.6 on 2021-08-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisco', '0005_alter_fisco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisco',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fiscofisco',
            options={},
        ),
    ]
