# Generated by Django 3.2.6 on 2021-08-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisco', '0006_auto_20210825_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisco',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fiscofisco',
            options={'managed': False},
        ),
    ]
