# Generated by Django 3.2.6 on 2021-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisco', '0007_auto_20210825_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fiscofisco',
        ),
        migrations.RemoveField(
            model_name='fisco',
            name='dataAlteracao',
        ),
        migrations.RemoveField(
            model_name='fisco',
            name='dataCadastro',
        ),
        migrations.RemoveField(
            model_name='fisco',
            name='regraTributo',
        ),
        migrations.AddField(
            model_name='fisco',
            name='dataalteracao',
            field=models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True),
        ),
        migrations.AddField(
            model_name='fisco',
            name='datacadastro',
            field=models.DateTimeField(auto_now_add=True, db_column='DataCadastro', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fisco',
            name='regratributo',
            field=models.CharField(blank=True, db_column='RegraTributo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fisco',
            name='ativo',
            field=models.BooleanField(blank=True, db_column='Ativo', null=True),
        ),
        migrations.AlterField(
            model_name='fisco',
            name='estado',
            field=models.CharField(blank=True, db_column='Estado', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fisco',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fisco',
            name='municipio',
            field=models.CharField(blank=True, db_column='Municipio', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fisco',
            name='nome',
            field=models.CharField(blank=True, db_column='Nome', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fisco',
            name='vencimento',
            field=models.DateTimeField(blank=True, db_column='Vencimento', null=True),
        ),
    ]
