# Generated by Django 3.2.6 on 2021-08-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nomefantasia', models.CharField(blank=True, db_column='NomeFantasia', max_length=250, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=20, null=True)),
                ('razaosocial', models.CharField(blank=True, db_column='RazaoSocial', max_length=350, null=True)),
                ('dataabertura', models.DateTimeField(blank=True, db_column='DataAbertura', null=True)),
                ('porte', models.CharField(blank=True, db_column='Porte', max_length=100, null=True)),
                ('atividadeprincipal', models.CharField(blank=True, db_column='AtividadePrincipal', max_length=250, null=True)),
                ('atividadesecundaria', models.CharField(blank=True, db_column='AtividadeSecundaria', max_length=250, null=True)),
                ('endereco', models.CharField(blank=True, db_column='Endereco', max_length=250, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=150, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=2, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=20, null=True)),
                ('telefoneadicional', models.CharField(blank=True, db_column='TelefoneAdicional', max_length=20, null=True)),
                ('situacaocadastral', models.CharField(blank=True, db_column='SituacaoCadastral', max_length=250, null=True)),
                ('datasituacaocadastral', models.DateTimeField(blank=True, db_column='DataSituacaoCadastral', null=True)),
                ('motivosituacaocadastral', models.CharField(blank=True, db_column='MotivoSituacaoCadastral', max_length=500, null=True)),
                ('situacaoespecial', models.CharField(blank=True, db_column='SituacaoEspecial', max_length=250, null=True)),
                ('datasituacaoespecial', models.DateTimeField(blank=True, db_column='DataSituacaoEspecial', null=True)),
                ('clientedesde', models.DateTimeField(blank=True, db_column='ClienteDesde', null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
                ('inscricaoestadual', models.CharField(blank=True, db_column='InscricaoEstadual', max_length=20, null=True)),
                ('codigomunicipio', models.CharField(blank=True, db_column='CodigoMunicipio', max_length=20, null=True)),
                ('inscricaomunicipal', models.CharField(blank=True, db_column='InscricaoMunicipal', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteCliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nomefantasia', models.CharField(blank=True, db_column='NomeFantasia', max_length=250, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=20, null=True)),
                ('razaosocial', models.CharField(blank=True, db_column='RazaoSocial', max_length=350, null=True)),
                ('dataabertura', models.DateField(blank=True, db_column='DataAbertura', null=True)),
                ('porte', models.CharField(blank=True, db_column='Porte', max_length=100, null=True)),
                ('atividadeprincipal', models.CharField(blank=True, db_column='AtividadePrincipal', max_length=250, null=True)),
                ('atividadesecundaria', models.CharField(blank=True, db_column='AtividadeSecundaria', max_length=250, null=True)),
                ('endereco', models.CharField(blank=True, db_column='Endereco', max_length=250, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=250, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=150, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=2, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=20, null=True)),
                ('telefoneadicional', models.CharField(blank=True, db_column='TelefoneAdicional', max_length=20, null=True)),
                ('situacaocadastral', models.CharField(blank=True, db_column='SituacaoCadastral', max_length=250, null=True)),
                ('datasituacaocadastral', models.DateField(blank=True, db_column='DataSituacaoCadastral', null=True)),
                ('motivosituacaocadastral', models.CharField(blank=True, db_column='MotivoSituacaoCadastral', max_length=500, null=True)),
                ('situacaoespecial', models.CharField(blank=True, db_column='SituacaoEspecial', max_length=250, null=True)),
                ('datasituacaoespecial', models.DateField(blank=True, db_column='DataSituacaoEspecial', null=True)),
                ('clientedesde', models.DateField(blank=True, db_column='ClienteDesde', null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
                ('inscricaoestadual', models.CharField(blank=True, db_column='InscricaoEstadual', max_length=20, null=True)),
                ('codigomunicipio', models.CharField(blank=True, db_column='CodigoMunicipio', max_length=20, null=True)),
                ('inscricaomunicipal', models.CharField(blank=True, db_column='InscricaoMunicipal', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Cliente_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteClienteempresa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('clienteid_id', models.IntegerField(db_column='ClienteID_id')),
                ('empresaid_id', models.IntegerField(db_column='EmpresaID_id')),
            ],
            options={
                'db_table': 'Cliente_clienteempresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
    ]
