# Generated by Django 3.2.6 on 2021-08-19 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('NomeFantasia', models.CharField(max_length=250, null=True)),
                ('CNPJ', models.CharField(max_length=20, null=True)),
                ('RazaoSocial', models.CharField(max_length=350, null=True)),
                ('DataAbertura', models.DateField(null=True)),
                ('Porte', models.CharField(max_length=100, null=True)),
                ('AtividadePrincipal', models.CharField(max_length=250, null=True)),
                ('AtividadeSecundaria', models.CharField(max_length=250, null=True)),
                ('Endereco', models.CharField(max_length=250, null=True)),
                ('Numero', models.CharField(max_length=10, null=True)),
                ('Complemento', models.CharField(max_length=150, null=True)),
                ('Bairro', models.CharField(max_length=250, null=True)),
                ('Cidade', models.CharField(max_length=150, null=True)),
                ('Estado', models.CharField(max_length=2, null=True)),
                ('CEP', models.CharField(max_length=10, null=True)),
                ('Email', models.EmailField(max_length=250, null=True)),
                ('Telefone', models.CharField(max_length=20, null=True)),
                ('TelefoneAdicional', models.CharField(max_length=20, null=True)),
                ('SituacaoCadastral', models.CharField(max_length=250, null=True)),
                ('DataSituacaoCadastral', models.DateField(null=True)),
                ('MotivoSituacaoCadastral', models.CharField(max_length=500, null=True)),
                ('SituacaoEspecial', models.CharField(max_length=250, null=True)),
                ('DataSituacaoEspecial', models.DateField(null=True)),
                ('ClienteDesde', models.DateField(null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField(null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
                ('InscricaoEstadual', models.CharField(max_length=20, null=True)),
                ('CodigoMunicipio', models.CharField(max_length=20, null=True)),
                ('InscricaoMunicipal', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
