# Generated by Django 3.2.6 on 2021-08-18 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoAcessoria',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Versao', models.CharField(max_length=20, null=True)),
                ('Bloco', models.CharField(max_length=20, null=True)),
                ('Campo', models.CharField(max_length=20, null=True)),
                ('DataCadastro', models.DateField(auto_now_add=True)),
                ('DataAlteracao', models.DateField(auto_now_add=True, null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
                ('Escopo', models.CharField(max_length=50)),
                ('PosicaoTXT', models.CharField(max_length=20, null=True)),
                ('Tamanho', models.CharField(max_length=20, null=True)),
                ('PaginaManual', models.CharField(max_length=100, null=True)),
                ('Observacao', models.CharField(max_length=250, null=True)),
                ('Registro', models.CharField(max_length=150, null=True)),
                ('OrdemClassificacao', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
