# Generated by Django 3.2.6 on 2021-08-19 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tributos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoAcessoria',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Versao', models.CharField(max_length=20, null=True)),
                ('Bloco', models.CharField(max_length=20, null=True)),
                ('Campo', models.CharField(max_length=20, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField(null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
                ('Escopo', models.CharField(max_length=50)),
                ('PosicaoTXT', models.CharField(max_length=20, null=True)),
                ('Tamanho', models.CharField(max_length=20, null=True)),
                ('PaginaManual', models.CharField(max_length=100, null=True)),
                ('Observacao', models.CharField(max_length=250, null=True)),
                ('Registro', models.CharField(max_length=150, null=True)),
                ('OrdemClassificacao', models.CharField(max_length=20, null=True)),
                ('BlocoCampoConfigID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tributos.blococampoconfig')),
            ],
        ),
    ]
