# Generated by Django 3.2.6 on 2021-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(blank=True, db_column='Senha', max_length=50, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=150)),
                ('email', models.EmailField(db_column='Email', max_length=150, unique=True)),
                ('cpf', models.CharField(db_column='CPF', max_length=20)),
                ('telefone', models.CharField(db_column='Telefone', max_length=20, null=True)),
                ('celular', models.CharField(db_column='Celular', max_length=20, null=True)),
                ('nomeusuario', models.CharField(db_column='NomeUsuario', max_length=50)),
                ('datacadastro', models.DateField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
                ('perfil', models.CharField(db_column='Perfil', max_length=50)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
