# Generated by Django 3.2.6 on 2021-08-17 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regras',
            fields=[
                ('id_regra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regra', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_Evento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('parametrizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrização.regras')),
            ],
            options={
                'ordering': ['tipo', 'descricao', 'parametrizacao'],
            },
        ),
    ]
