# Generated by Django 3.2.6 on 2021-08-19 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ObrigacaoAcessoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100, null=True)),
                ('ContaReferecial', models.CharField(max_length=20, null=True)),
                ('DescContaReferencial', models.CharField(max_length=150, null=True)),
                ('Aliquota', models.DecimalField(decimal_places=38, max_digits=38, null=True)),
                ('RegimeTributario', models.CharField(max_length=50, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField()),
                ('Ativo', models.BooleanField(default=True, null=True)),
                ('ObrigacaoAcessorialID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ObrigacaoAcessoria.obrigacaoacessoria')),
            ],
        ),
        migrations.CreateModel(
            name='Parametrizacao',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField()),
                ('Ativo', models.BooleanField(default=True, null=True)),
                ('EventoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrização.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=50)),
                ('Nome', models.CharField(max_length=100, null=True)),
                ('Descricao', models.CharField(max_length=150, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField(null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrizacaoRegra',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ParametrizacaoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrização.parametrizacao')),
                ('RegraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrização.regra')),
            ],
        ),
    ]
