# Generated by Django 3.2.6 on 2021-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=150, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'Cnae',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codigoprefeitura',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigoibge', models.CharField(blank=True, db_column='CodigoIBGE', max_length=20, null=True)),
                ('descricaoprefeitura', models.CharField(blank=True, db_column='DescricaoPrefeitura', max_length=150, null=True)),
                ('codigoservico', models.CharField(blank=True, db_column='CodigoServico', max_length=20, null=True)),
                ('descricaoservico', models.CharField(blank=True, db_column='DescricaoServico', max_length=100, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'CodigoPrefeitura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deparacnaecodigoprefeitura',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DeParaCnaeCodigoPrefeitura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deparacnaeleicomplementar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DeParaCnaeLeiComplementar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deparaleicomplementarretencao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DeParaLeiComplementarRetencao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True)),
                ('xml', models.BooleanField(blank=True, null=True)),
                ('txt', models.BooleanField(blank=True, null=True)),
                ('pdf', models.BooleanField(blank=True, null=True)),
                ('doc', models.BooleanField(blank=True, null=True)),
                ('xls', models.BooleanField(blank=True, null=True)),
                ('ofx', models.BooleanField(blank=True, null=True)),
                ('csv', models.BooleanField(blank=True, null=True)),
                ('json', models.BooleanField(blank=True, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
                ('xlsx', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('contareferencial', models.CharField(blank=True, db_column='ContaReferencial', max_length=20, null=True)),
                ('desccontareferencial', models.CharField(blank=True, db_column='DescContaReferencial', max_length=150, null=True)),
                ('aliquota', models.DecimalField(blank=True, db_column='Aliquota', decimal_places=0, max_digits=38, null=True)),
                ('regimetributario', models.CharField(blank=True, db_column='RegimeTributario', max_length=50, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'Evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventogrupo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'EventoGrupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geracaocredito',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'GeracaoCredito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupoevento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'GrupoEvento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leicomplementar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=150, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'LeiComplementar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametrizacao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'Parametrizacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametrizacaoregra',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ParametrizacaoRegra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodicidade',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'Periodicidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=150, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'Regra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regradocumento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'RegraDocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retencaofonte',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True)),
                ('aliquota', models.CharField(blank=True, db_column='Aliquota', max_length=20, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=150, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'Retencaofonte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoarquivo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=50, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
            ],
            options={
                'db_table': 'TipoArquivo',
                'managed': False,
            },
        ),
    ]
