# Generated by Django 3.2.6 on 2021-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrização', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='DataAlteracao',
            field=models.DateTimeField(null=True),
        ),
    ]
