# Generated by Django 3.2.6 on 2021-08-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planocontas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planocontasitem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('datainicio', models.DateField(blank=True, db_column='DataInicio', null=True)),
                ('datafim', models.DateField(blank=True, db_column='DataFim', null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=1, null=True)),
                ('contasuperior', models.CharField(blank=True, db_column='ContaSuperior', max_length=50, null=True)),
                ('nivel', models.IntegerField(blank=True, db_column='Nivel', null=True)),
                ('natureza', models.IntegerField(blank=True, db_column='Natureza', null=True)),
                ('orientacoes', models.CharField(blank=True, db_column='Orientacoes', max_length=500, null=True)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, db_column='DataCadastro')),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', default=True, null=True)),
                ('planocontasrefencialid', models.ForeignKey(db_column='PlanoContasReferencialID', on_delete=django.db.models.deletion.CASCADE, to='planocontas.planocontasreferencial')),
            ],
        ),
    ]
