# Generated by Django 3.2.6 on 2021-08-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planocontas', '0002_planocontasitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planocontasitem',
            options={'managed': False},
        ),
    ]
