# Generated by Django 3.2.6 on 2021-08-16 22:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFeriado', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id_calendario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('municipio', models.CharField(max_length=100)),
                ('feriado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullcalendar.feriadocalendario')),
            ],
        ),
    ]
