# Generated by Django 3.2.6 on 2021-08-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CNPJ', models.CharField(max_length=20)),
                ('DataAbertura', models.DateField(null=True)),
                ('Bairro', models.CharField(max_length=150, null=True)),
                ('Municipio', models.CharField(max_length=150, null=True)),
                ('Estado', models.CharField(max_length=2, null=True)),
                ('RazaoSocial', models.CharField(max_length=250, null=True)),
                ('Email', models.EmailField(max_length=150, null=True)),
                ('NomeFantasia', models.CharField(max_length=250, null=True)),
                ('Porte', models.CharField(max_length=100, null=True)),
                ('Telefone', models.CharField(max_length=20, null=True)),
                ('TelefoneAdicional', models.CharField(max_length=20, null=True)),
                ('SituacaoCadastral', models.CharField(max_length=250, null=True)),
                ('DataSituacaoCadastral', models.DateField(null=True)),
                ('MotivoSituacaoCadastral', models.CharField(max_length=500, null=True)),
                ('SituacaoEspecial', models.CharField(max_length=250, null=True)),
                ('DataSituacaoEspecial', models.DateField(null=True)),
                ('AtividadePrincipal', models.CharField(max_length=250, null=True)),
                ('AtividadeSecundaria', models.CharField(max_length=250, null=True)),
                ('Endereco', models.CharField(max_length=250, null=True)),
                ('Numero', models.CharField(max_length=10, null=True)),
                ('Complemento', models.CharField(max_length=150, null=True)),
                ('Cep', models.CharField(max_length=10, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField(null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
