# Generated by Django 3.2.6 on 2021-08-11 16:17

import django.core.validators
from django.db import migrations, models
import django_cpf_cnpj.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=80)),
                ('nome_fantasia', models.CharField(max_length=80)),
                ('porte', models.CharField(max_length=100)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('descricao_principal', models.CharField(max_length=100)),
                ('descricao_secundaria', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('adPhoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=100)),
                ('uf', models.CharField(choices=[('RO', 'Rondônia'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('PA', 'Pará'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal')], max_length=2)),
                ('situacao_cadastral', models.CharField(max_length=250)),
                ('data_situacao_cadastral', models.DateField()),
                ('motivo_situacao_cadastral', models.CharField(max_length=250)),
                ('situacao_especial', models.CharField(max_length=250)),
                ('data_situacao_especial', models.DateField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
