# Generated by Django 3.2.6 on 2021-08-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoCampoConfig',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Bloco', models.CharField(max_length=50, null=True)),
                ('Campo', models.CharField(max_length=50, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField(null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Esteira',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RegimeTributario',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField(null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsteiraCampo',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Valor', models.DecimalField(decimal_places=38, max_digits=38, null=True)),
                ('BlocoCampoConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tributos.blococampoconfig')),
                ('EsteiraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tributos.esteira')),
            ],
        ),
        migrations.AddField(
            model_name='esteira',
            name='RegimeTributarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tributos.regimetributario'),
        ),
        migrations.CreateModel(
            name='EmpresaRegimeTributario',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('RegimeTributarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tributos.regimetributario')),
            ],
        ),
        migrations.CreateModel(
            name='ControleTributos',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CodigoContabil', models.CharField(max_length=50, null=True)),
                ('DescricaoCodigoContabil', models.CharField(max_length=150, null=True)),
                ('MesCompetencia', models.IntegerField(null=True)),
                ('AnoCompetencia', models.IntegerField(null=True)),
                ('ValorProvisaoRecolher', models.DecimalField(decimal_places=38, max_digits=38, null=True)),
                ('TipoLancamentoPrevisao', models.CharField(max_length=50, null=True)),
                ('Historico', models.CharField(max_length=250, null=True)),
                ('Vencimento', models.DateField(null=True)),
                ('DataRecolhimento', models.DateField(null=True)),
                ('ValorRecolhimento', models.DecimalField(decimal_places=38, max_digits=38, null=True)),
                ('TipoLancamento', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('MensagemAviso', models.CharField(max_length=250, null=True)),
                ('MensagemRecomendacao', models.CharField(max_length=250, null=True)),
                ('DataCadastro', models.DateTimeField(editable=False)),
                ('DataAlteracao', models.DateTimeField(null=True)),
                ('Ativo', models.BooleanField(default=True, null=True)),
                ('EsteiraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tributos.esteira')),
            ],
        ),
    ]
